pub const test1 = [_][2][]const u8{
    .{ "kitten", "sitting" },
    .{ "test", "testdata" },
};

pub const test2 = [_][2][]const u8{
    .{ "aftermath", "qualify" },
    .{ "knowledge", "permit" },
    .{ "sentence", "cross" },
    .{ "divide", "majestic" },
    .{ "cheer", "derive" },
    .{ "stingy", "industrious" },
    .{ "stare", "derive" },
    .{ "silk", "obnoxious" },
    .{ "thin", "jobless" },
    .{ "murmur", "cute" },
    .{ "door", "paint" },
    .{ "walk", "probable" },
    .{ "bait", "lethal" },
    .{ "marked", "choke" },
    .{ "clothe", "be" },
    .{ "force", "boats" },
    .{ "bath", "hinder" },
    .{ "warm", "vanish" },
    .{ "sparkling", "false" },
    .{ "wakeful", "science" },
    .{ "small", "fold" },
    .{ "bite", "unbiased" },
    .{ "tendency", "exciting" },
    .{ "hydrant", "axiomatic" },
    .{ "arithmetic", "push" },
    .{ "draw", "illumine" },
    .{ "trousers", "vein" },
    .{ "heartbreaking", "dedicate" },
    .{ "discussion", "craven" },
    .{ "able", "ornament" },
    .{ "remake", "rambunctious" },
    .{ "color", "ahead" },
    .{ "wet", "bee" },
    .{ "teach", "do" },
    .{ "defiant", "crate" },
    .{ "scam", "frog" },
    .{ "true", "battle" },
    .{ "left", "surpass" },
    .{ "contrive", "follow" },
    .{ "stale", "money" },
    .{ "superficial", "smiling" },
    .{ "psychotic", "recess" },
    .{ "dramatic", "add" },
    .{ "debonair", "breath" },
    .{ "violet", "political" },
    .{ "boorish", "defiant" },
    .{ "sloppy", "neglect" },
    .{ "chess", "unwritten" },
    .{ "sincere", "walk" },
    .{ "diminish", "painstaking" },
};
